In [33]:
import numpy as np
import os 
import argparse
import cmath
import random
j= complex(0,1)
Y_SIZE=512
H_SIZE=32
SIG = 0.005
LAMBDA = 0.2






In [6]:
## Constructing X and F
x = np.random.choice([1+1j,1-1j,-1+1j,-1-1j],size=Y_SIZE)
X = np.diag(x,k=0)
F = np.empty((Y_SIZE,H_SIZE),dtype=np.csingle)
for i in range(F.shape[0]):
    for k in range(F.shape[1]):
        F[i][k] = cmath.exp(1j*(2*cmath.pi*i*k/512))
n = np.random.normal(scale=SIG**2,size=Y_SIZE)



In [3]:
## Constructing h
p = np.asarray([np.exp(-1*(LAMBDA)*i) for i in range(H_SIZE)])
p = p/np.sum(p**2)
a = np.random.normal(scale=0.5,size=H_SIZE)
b = np.random.normal(scale=0.5,size=H_SIZE)

h = np.multiply(p,a+b*j)

## Observations 
A = np.matmul(X,F)

y = np.matmul(A,h) + n

## LSE

h_,d,r,s = np.linalg.lstsq(A,y)
# d = np.sqrt(np.sum((h-h_)**2)/np.sum(h**2))

print(np.matmul(A,h)[:4])
print("h vector was : ",h)
print("h_ vector is :",h_)
print("Normalized difference :",d)




[ 0.16848229+0.38503435j  0.36381848-0.15139222j  0.13634997+0.34132001j
 -0.31774174+0.12341225j]
h vector was :  [-3.06840646e-01+1.55006539e-01j -7.50834616e-02-6.97704577e-02j
  1.52932866e-01+3.43126220e-02j -9.50670853e-03-4.47938312e-02j
 -4.62561439e-02+3.11164135e-02j -4.15826029e-03-1.65755012e-02j
  1.14242969e-01-8.66660970e-02j -7.51631395e-02-6.12160927e-02j
 -6.59997266e-02-8.48337068e-03j  3.25575351e-03+3.26737228e-02j
  3.21892058e-02-3.56485147e-02j -2.14499944e-02-1.16031630e-02j
 -1.50783207e-02-3.12849499e-02j  2.41011639e-02+1.71397381e-02j
  1.34928624e-02-2.20065699e-02j  4.63896212e-03-4.56213384e-03j
 -7.94457767e-03+4.57534586e-03j -1.01238558e-04+5.95048543e-05j
  1.66002467e-03+1.88375106e-03j  7.24680670e-03+5.87791385e-03j
  7.36171755e-04-3.34905548e-03j  4.86302898e-03+1.31028192e-03j
 -3.34183566e-03+2.60552685e-03j -2.26303559e-03+1.74940080e-03j
 -2.18203151e-03+1.80853364e-04j -2.92912957e-04+1.44226304e-03j
 -6.56349441e-04-3.35805360e-04j -1.6899

/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  app.launch_new_instance()


In [34]:
### Sparse h 
h2 = h.copy()
inds = []
for i in random.sample(range(0,H_SIZE),H_SIZE-6):
    inds.append(i)
    h2[i] = 0

y2 = np.matmul(A,h2) + n

# h_,d,r,s = np.linalg.lstsq(A,y2)

print("Sparse h vector was : ",h2)
print(" h_ vector is :",h_)

Sparse h vector was :  [ 0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
 -0.04625614+3.11164135e-02j -0.00415826-1.65755012e-02j
  0.11424297-8.66660970e-02j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.02410116+1.71397381e-02j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
 -0.00218203+1.80853364e-04j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.        +0.00000000e+00j  0.        +0.00000000e+00j
  0.00030126-1.81660275e-06j  0.        +0.00000000e+00j]
 h_ vector is : [-6.73474652e-07-1.08542525e-06j -7.50837135e-02

In [17]:
X_ = X.copy()
inds = [(i,i) for i in range(180)]
inds.extend([(511-i,511-i) for i in range(180)])
# print(inds)
X_[inds] = 0 


In [20]:
A

array([[-1.        -1.j        , -1.        -1.j        ,
        -1.        -1.j        , ..., -1.        -1.j        ,
        -1.        -1.j        , -1.        -1.j        ],
       [-1.        +1.j        , -1.01219626+0.98765318j,
        -1.02424005+0.97515759j, ..., -1.28575769+0.58892033j,
        -1.29288787+0.57309777j, -1.29982328+0.55718887j],
       [-1.        -1.j        , -0.97515759-1.02424005j,
        -0.94972777-1.04786313j, ..., -0.10403597-1.41038167j,
        -0.06939214-1.4125101j , -0.03470653-1.41378766j],
       ...,
       [-1.        +1.j        , -0.96251513+1.03612958j,
        -0.92372587+1.070855j  , ...,  0.3938863 +1.35825387j,
         0.44361296+1.34283563j,  0.49273846+1.32559755j],
       [-1.        +1.j        , -0.97515759+1.02424005j,
        -0.94972777+1.04786313j, ..., -0.10403597+1.41038167j,
        -0.06939214+1.4125101j , -0.03470653+1.41378766j],
       [ 1.        +1.j        ,  1.01219626+0.98765318j,
         1.02424005+0.97515759

In [26]:
np.asmatrix(A).getH()

matrix([[-1.        +1.j        , -1.        -1.j        ,
         -1.        +1.j        , ..., -1.        -1.j        ,
         -1.        -1.j        ,  1.        -1.j        ],
        [-1.        +1.j        , -1.01219626-0.98765318j,
         -0.97515759+1.02424005j, ..., -0.96251513-1.03612958j,
         -0.97515759-1.02424005j,  1.01219626-0.98765318j],
        [-1.        +1.j        , -1.02424005-0.97515759j,
         -0.94972777+1.04786313j, ..., -0.92372587-1.070855j  ,
         -0.94972777-1.04786313j,  1.02424005-0.97515759j],
        ...,
        [-1.        +1.j        , -1.28575769-0.58892033j,
         -0.10403597+1.41038167j, ...,  0.3938863 -1.35825387j,
         -0.10403597-1.41038167j,  1.28575769-0.58892033j],
        [-1.        +1.j        , -1.29288787-0.57309777j,
         -0.06939214+1.4125101j , ...,  0.44361296-1.34283563j,
         -0.06939214-1.4125101j ,  1.29288787-0.57309777j],
        [-1.        +1.j        , -1.29982328-0.55718887j,
         -0.0

In [51]:
def pinv(A):
    Ah = np.asmatrix(A).getH()
    return  np.matmul(np.linalg.inv(np.matmul(Ah,A)),Ah)

Somp = []
r = y2
ko = 6
Ah = np.asmatrix(A).getH()
for k in range(ko):
    t_ = np.matmul(Ah,r)
    print(t_[0][0][0][0][0][0])
    t = np.argmax(np.abs(np.matmul(Ah,r)))
    Somp.append(int(t))
    p = np.matmul(A[:,Somp],pinv(A[:,Somp]))
    r = np.matmul((np.eye(512) - p),y2)
    
    
                  
    
    

[[-6.89638044e-04-1.11147545e-03j -2.57927688e-04-3.96792132e-05j
   7.78493393e-04+7.47483782e-04j -6.07279464e-04+7.38918354e-05j
  -4.73661061e+01+3.18622097e+01j -4.25791068e+00-1.69725567e+01j
   1.16983969e+02-8.87467915e+01j -3.54318439e-04+4.45158164e-04j
  -3.70804301e-04-5.22938984e-05j  2.86226811e-04+2.32428331e-04j
   5.59825555e-04+1.01703571e-03j  4.00029355e-04+1.42649049e-04j
   5.76213886e-04-1.52719820e-04j  2.46802887e+01+1.75506851e+01j
  -3.00260543e-04+1.26180702e-03j -2.21304037e-04+8.98050559e-04j
   2.64901047e-04-8.54592910e-05j  2.06751970e-04-8.59828002e-04j
  -1.31184950e-04-1.57663668e-04j  2.52760152e-05-1.23148207e-04j
  -1.69897784e-04+2.22166323e-04j -6.82582755e-04-4.30053083e-04j
   8.74916055e-04-7.42775777e-04j -6.58651153e-04-9.34729179e-04j
  -2.23470058e+00+1.85275943e-01j -6.06843570e-04-5.46899509e-04j
  -6.43006533e-04-1.47120864e-04j -1.07159174e-03-2.75318049e-04j
   1.07503739e-04+1.50093634e-03j -1.08615649e-04+8.92260384e-04j
   3.08093

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 512)

In [29]:
a = np.array([[1-1j,2-1j],[1-1j,1-1j]])
np.matmul(a,np.asarray([1-1j,1-1j]))

array([1.-5.j, 0.-4.j])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])